from __future__ import annotations
import collections.abc
import numpy
import numpy.typing
import typing
__all__: list[str] = ['BitVec', 'CandidateExport', 'DISTANCE', 'ExplorationScore', 'FinalizationScore', 'Function', 'LINEAR', 'LOGARITHMIC', 'Matrix', 'MatrixWithData', 'NullSpace', 'POLYNOM', 'PolicyConfig', 'RNG', 'Result', 'SIGMOID', 'ScoringFunction', 'Stats', 'Tensor3D', 'ToddGenerator', 'TohpeGenerator', 'get_omp_threads', 'policy_iteration', 'set_omp_threads']
class BitVec:
    @staticmethod
    def from_numpy(a: typing.Annotated[numpy.typing.ArrayLike, numpy.bool]) -> BitVec:
        ...
    def __getitem__(self, arg0: typing.SupportsInt) -> bool:
        ...
    @typing.overload
    def __init__(self, n: typing.SupportsInt) -> None:
        ...
    @typing.overload
    def __init__(self, n: typing.SupportsInt, bits: collections.abc.Sequence[bool]) -> None:
        ...
    def __ixor__(self, arg0: BitVec) -> BitVec:
        ...
    def __len__(self) -> int:
        ...
    def __repr__(self) -> str:
        ...
    def __setitem__(self, arg0: typing.SupportsInt, arg1: bool) -> None:
        ...
    def __xor__(self, arg0: BitVec) -> BitVec:
        ...
    def count(self) -> int:
        ...
    def size(self) -> int:
        ...
    def to_list(self) -> list[bool]:
        ...
    def to_numpy(self) -> numpy.typing.NDArray[numpy.bool]:
        ...
class CandidateExport:
    def __getstate__(self) -> tuple:
        ...
    def __init__(self) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, arg0: tuple) -> None:
        ...
    @property
    def basis_dim(self) -> int:
        ...
    @basis_dim.setter
    def basis_dim(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def bucket_size(self) -> int:
        ...
    @bucket_size.setter
    def bucket_size(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def final_score(self) -> float:
        ...
    @final_score.setter
    def final_score(self, arg0: typing.SupportsFloat) -> None:
        ...
    @property
    def k(self) -> int:
        ...
    @k.setter
    def k(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def l(self) -> int:
        ...
    @l.setter
    def l(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def num_better_dim(self) -> int:
        ...
    @num_better_dim.setter
    def num_better_dim(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def num_better_pool_score(self) -> int:
        ...
    @num_better_pool_score.setter
    def num_better_pool_score(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def num_better_red(self) -> int:
        ...
    @num_better_red.setter
    def num_better_red(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def pool_score(self) -> float:
        ...
    @pool_score.setter
    def pool_score(self, arg0: typing.SupportsFloat) -> None:
        ...
    @property
    def reduction(self) -> int:
        ...
    @reduction.setter
    def reduction(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def tohpe_dim(self) -> int:
        ...
    @tohpe_dim.setter
    def tohpe_dim(self, arg0: typing.SupportsInt) -> None:
        ...
class ExplorationScore:
    def __getitem__(self, arg0: typing.SupportsInt) -> float:
        ...
    def __getstate__(self) -> tuple:
        ...
    @typing.overload
    def __init__(self, weights: collections.abc.Sequence[typing.SupportsFloat] = [0.0, 0.0, 0.0, 0.0, 0.0], centers: collections.abc.Sequence[typing.SupportsFloat] = [0.0, 0.0, 0.0, 0.0, 0.0], sc: ScoringFunction = ...) -> None:
        ...
    @typing.overload
    def __init__(self, weights: collections.abc.Sequence[typing.SupportsFloat] = [0.0, 0.0, 0.0, 0.0, 0.0], centers: collections.abc.Sequence[typing.SupportsFloat] = [0.0, 0.0, 0.0, 0.0, 0.0], pow: typing.SupportsFloat = 1.0) -> None:
        ...
    def __len__(self) -> int:
        ...
    def __setstate__(self, arg0: tuple) -> None:
        ...
    def pow(self) -> float:
        ...
class FinalizationScore:
    def __getitem__(self, arg0: typing.SupportsInt) -> float:
        ...
    def __getstate__(self) -> tuple:
        ...
    @typing.overload
    def __init__(self, weights: collections.abc.Sequence[typing.SupportsFloat] = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], centers: collections.abc.Sequence[typing.SupportsFloat] = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], sc: ScoringFunction = ...) -> None:
        ...
    @typing.overload
    def __init__(self, weights: collections.abc.Sequence[typing.SupportsFloat] = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], centers: collections.abc.Sequence[typing.SupportsFloat] = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], pow: typing.SupportsFloat = 1.0) -> None:
        ...
    def __len__(self) -> int:
        ...
    def __setstate__(self, arg0: tuple) -> None:
        ...
    def pow(self) -> float:
        ...
class Function:
    """
    Members:
    
      LINEAR
    
      POLYNOM
    
      DISTANCE
    
      LOGARITHMIC
    
      SIGMOID
    """
    DISTANCE: typing.ClassVar[Function]  # value = <Function.DISTANCE: 2>
    LINEAR: typing.ClassVar[Function]  # value = <Function.LINEAR: 0>
    LOGARITHMIC: typing.ClassVar[Function]  # value = <Function.LOGARITHMIC: 3>
    POLYNOM: typing.ClassVar[Function]  # value = <Function.POLYNOM: 1>
    SIGMOID: typing.ClassVar[Function]  # value = <Function.SIGMOID: 4>
    __members__: typing.ClassVar[dict[str, Function]]  # value = {'LINEAR': <Function.LINEAR: 0>, 'POLYNOM': <Function.POLYNOM: 1>, 'DISTANCE': <Function.DISTANCE: 2>, 'LOGARITHMIC': <Function.LOGARITHMIC: 3>, 'SIGMOID': <Function.SIGMOID: 4>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class Matrix:
    __hash__: typing.ClassVar[None] = None
    @staticmethod
    def from_numpy(arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.bool]) -> Matrix:
        ...
    @staticmethod
    def from_rows(rows: collections.abc.Sequence[BitVec]) -> Matrix:
        ...
    @staticmethod
    def identity(n: typing.SupportsInt) -> Matrix:
        ...
    @staticmethod
    def zeros(rows: typing.SupportsInt, cols: typing.SupportsInt) -> Matrix:
        ...
    def __add__(self, arg0: Matrix) -> Matrix:
        ...
    def __eq__(self, arg0: Matrix) -> bool:
        ...
    def __getitem__(self, arg0: typing.SupportsInt) -> BitVec:
        ...
    def __getstate__(self) -> numpy.typing.NDArray[numpy.bool]:
        ...
    def __iadd__(self, arg0: Matrix) -> Matrix:
        ...
    def __init__(self, rows: typing.SupportsInt, cols: typing.SupportsInt) -> None:
        ...
    def __len__(self) -> int:
        ...
    def __matmul__(self, arg0: BitVec) -> BitVec:
        ...
    def __mul__(self, arg0: Matrix) -> Matrix:
        ...
    def __ne__(self, arg0: Matrix) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setitem__(self, arg0: typing.SupportsInt, arg1: BitVec) -> None:
        ...
    def __setstate__(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.bool]) -> None:
        ...
    def append_down_inplace(self, arg0: Matrix) -> Matrix:
        ...
    def append_right_inplace(self, arg0: Matrix) -> Matrix:
        ...
    def seed(self, base_seed: typing.SupportsInt = 0, add_seed: typing.SupportsInt = 0) -> int:
        ...
    def to_numpy(self) -> numpy.typing.NDArray[numpy.bool]:
        ...
    def transpose(self) -> Matrix:
        ...
    @property
    def cols(self) -> int:
        ...
    @property
    def rows(self) -> int:
        ...
class MatrixWithData:
    def __init__(self, P: Matrix) -> None:
        ...
    def tohpe_dim(self) -> int:
        ...
    @property
    def P(self) -> Matrix:
        ...
    @property
    def tohpe_basis(self) -> Matrix:
        ...
class NullSpace:
    def apply(self, arg0: BitVec) -> Matrix:
        ...
    def linear_combination(self, arg0: BitVec) -> BitVec:
        ...
    def rank_divergence(self, arg0: BitVec) -> int:
        ...
    @property
    def P(self) -> Matrix:
        ...
    @property
    def basis(self) -> Matrix:
        ...
    @property
    def z(self) -> BitVec:
        ...
class PolicyConfig:
    selection: str
    try_only_tohpe: bool
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, ExplorationScore: ExplorationScore = ..., FinalizationScore: FinalizationScore = ..., selection: str = 'greedy', temperature: typing.SupportsFloat = 0.0, non_improving_prob: typing.SupportsFloat = 0.0, gen_part: typing.SupportsFloat = 1.0, num_samples: typing.SupportsInt = 64, num_candidates: typing.SupportsInt = 1, top_pool: typing.SupportsInt = 1, max_from_single_ns: typing.SupportsInt = 10, min_reduction: typing.SupportsInt = 0, max_reduction: typing.SupportsInt = 2147483647, max_z_to_research: typing.SupportsInt = 1073741824, min_pool_size: typing.SupportsInt = 1, max_tohpe: typing.SupportsInt = 1, threads: typing.SupportsInt = 1, tohpe_sample: typing.SupportsInt = 1, try_only_tohpe: bool = True) -> None:
        ...
    def __repr__(self) -> str:
        ...
    @property
    def gen_part(self) -> float:
        ...
    @gen_part.setter
    def gen_part(self, arg0: typing.SupportsFloat) -> None:
        ...
    @property
    def max_from_single_ns(self) -> int:
        ...
    @max_from_single_ns.setter
    def max_from_single_ns(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def max_reduction(self) -> int:
        ...
    @max_reduction.setter
    def max_reduction(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def max_tohpe(self) -> int:
        ...
    @max_tohpe.setter
    def max_tohpe(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def max_z_to_research(self) -> int:
        ...
    @max_z_to_research.setter
    def max_z_to_research(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def min_pool_size(self) -> int:
        ...
    @min_pool_size.setter
    def min_pool_size(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def min_reduction(self) -> int:
        ...
    @min_reduction.setter
    def min_reduction(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def non_improving_prob(self) -> float:
        ...
    @non_improving_prob.setter
    def non_improving_prob(self, arg0: typing.SupportsFloat) -> None:
        ...
    @property
    def num_candidates(self) -> int:
        ...
    @num_candidates.setter
    def num_candidates(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def num_samples(self) -> int:
        ...
    @num_samples.setter
    def num_samples(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def temperature(self) -> float:
        ...
    @temperature.setter
    def temperature(self, arg0: typing.SupportsFloat) -> None:
        ...
    @property
    def threads(self) -> int:
        ...
    @threads.setter
    def threads(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def tohpe_sample(self) -> int:
        ...
    @tohpe_sample.setter
    def tohpe_sample(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def top_pool(self) -> int:
        ...
    @top_pool.setter
    def top_pool(self, arg0: typing.SupportsInt) -> None:
        ...
class RNG:
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, seed: typing.SupportsInt) -> None:
        ...
    def rand_double(self, low: typing.SupportsFloat = 0.0, high: typing.SupportsFloat = 1.0) -> float:
        ...
    def rand_int(self, arg0: typing.SupportsInt, arg1: typing.SupportsInt) -> int:
        ...
    def random(self) -> int:
        ...
    def sample_bitvec(self, arg0: typing.SupportsInt) -> BitVec:
        ...
    def sample_unique_bitvecs(self, arg0: typing.SupportsInt, arg1: typing.SupportsInt, arg2: typing.SupportsFloat) -> list[BitVec]:
        ...
    def seed(self, arg0: typing.SupportsInt) -> None:
        ...
class Result:
    stats: Stats
    def __init__(self) -> None:
        ...
    def __repr__(self) -> str:
        ...
    @property
    def chosen(self) -> list[CandidateExport]:
        ...
    @chosen.setter
    def chosen(self, arg0: collections.abc.Sequence[CandidateExport]) -> None:
        ...
    @property
    def seed(self) -> int:
        ...
    @seed.setter
    def seed(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def states(self) -> list[Matrix]:
        ...
    @states.setter
    def states(self, arg0: collections.abc.Sequence[Matrix]) -> None:
        ...
class ScoringFunction:
    type: Function
    def __getstate__(self) -> tuple:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, type: Function = ..., pow: typing.SupportsFloat = 2.0) -> None:
        ...
    def __setstate__(self, arg0: tuple) -> None:
        ...
    @property
    def pow(self) -> float:
        ...
    @pow.setter
    def pow(self, arg0: typing.SupportsFloat) -> None:
        ...
class Stats:
    def __getstate__(self) -> tuple:
        ...
    def __init__(self) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, arg0: tuple) -> None:
        ...
    @property
    def accepted(self) -> int:
        ...
    @accepted.setter
    def accepted(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def accepted_non_improving(self) -> int:
        ...
    @accepted_non_improving.setter
    def accepted_non_improving(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def accepted_tohpe(self) -> int:
        ...
    @accepted_tohpe.setter
    def accepted_tohpe(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def max_basis(self) -> int:
        ...
    @max_basis.setter
    def max_basis(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def max_bucket(self) -> int:
        ...
    @max_bucket.setter
    def max_bucket(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def max_reduction(self) -> int:
        ...
    @max_reduction.setter
    def max_reduction(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def max_score(self) -> float:
        ...
    @max_score.setter
    def max_score(self, arg0: typing.SupportsFloat) -> None:
        ...
    @property
    def max_tohpe_dim(self) -> float:
        ...
    @max_tohpe_dim.setter
    def max_tohpe_dim(self, arg0: typing.SupportsFloat) -> None:
        ...
    @property
    def mean_basis(self) -> float:
        ...
    @mean_basis.setter
    def mean_basis(self, arg0: typing.SupportsFloat) -> None:
        ...
    @property
    def mean_mr(self) -> float:
        ...
    @mean_mr.setter
    def mean_mr(self, arg0: typing.SupportsFloat) -> None:
        ...
    @property
    def mean_reduction(self) -> float:
        ...
    @mean_reduction.setter
    def mean_reduction(self, arg0: typing.SupportsFloat) -> None:
        ...
    @property
    def mean_score(self) -> float:
        ...
    @mean_score.setter
    def mean_score(self, arg0: typing.SupportsFloat) -> None:
        ...
    @property
    def mean_tohpe_dim(self) -> float:
        ...
    @mean_tohpe_dim.setter
    def mean_tohpe_dim(self, arg0: typing.SupportsFloat) -> None:
        ...
    @property
    def nonzero(self) -> int:
        ...
    @nonzero.setter
    def nonzero(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def total(self) -> int:
        ...
    @total.setter
    def total(self, arg0: typing.SupportsInt) -> None:
        ...
class Tensor3D:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: Tensor3D) -> bool:
        ...
    @typing.overload
    def __init__(self, arg0: typing.SupportsInt) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: Matrix) -> None:
        ...
    def __ne__(self, arg0: Tensor3D) -> bool:
        ...
    def get(self, arg0: typing.SupportsInt, arg1: typing.SupportsInt, arg2: typing.SupportsInt) -> bool:
        ...
    def to_numpy(self) -> numpy.typing.NDArray[numpy.bool]:
        ...
    @property
    def n(self) -> int:
        ...
class ToddGenerator:
    def __init__(self, data: MatrixWithData) -> None:
        ...
    def make(self, z: BitVec) -> NullSpace:
        ...
    def make1(self, row: typing.SupportsInt) -> NullSpace:
        ...
    def make2(self, row1: typing.SupportsInt, row2: typing.SupportsInt) -> NullSpace:
        ...
    @property
    def P(self) -> Matrix:
        ...
class TohpeGenerator:
    def __init__(self, data: MatrixWithData) -> None:
        ...
    def best_z(self, arg0: BitVec) -> BitVec:
        ...
    def make(self, z: BitVec) -> NullSpace:
        ...
    def make1(self, row: typing.SupportsInt) -> NullSpace:
        ...
    def make2(self, row1: typing.SupportsInt, row2: typing.SupportsInt) -> NullSpace:
        ...
    @property
    def P(self) -> Matrix:
        ...
def get_omp_threads() -> int:
    ...
def policy_iteration(cur_mat: Matrix, policy_cfg: PolicyConfig = ..., seed: typing.SupportsInt = 21, add_seed: typing.SupportsInt = 0) -> Result:
    ...
def set_omp_threads(arg0: typing.SupportsInt) -> None:
    ...
DISTANCE: Function  # value = <Function.DISTANCE: 2>
LINEAR: Function  # value = <Function.LINEAR: 0>
LOGARITHMIC: Function  # value = <Function.LOGARITHMIC: 3>
POLYNOM: Function  # value = <Function.POLYNOM: 1>
SIGMOID: Function  # value = <Function.SIGMOID: 4>
