"""
GF(2) Matrix + bitvector bindings
"""
from __future__ import annotations
import collections.abc
import numpy
import numpy.typing
import typing
__all__: list[str] = ['BitVec', 'L_expansion', 'Matrix', 'NullSpace', 'PivotMap', 'Tensor3D', 'ToddGenerator', 'TohpeGenerator', 'build_X', 'build_v', 'eliminate_duplications_inplace', 'extract_basis', 'gauss_elimination_inplace', 'swap_rows_inplace']
class BitVec:
    @staticmethod
    def from_numpy(array: typing.Annotated[numpy.typing.ArrayLike, numpy.bool]) -> BitVec:
        ...
    def __and__(self, arg0: BitVec) -> BitVec:
        ...
    def __getitem__(self, arg0: typing.SupportsInt) -> bool:
        ...
    @typing.overload
    def __init__(self, n: typing.SupportsInt) -> None:
        ...
    @typing.overload
    def __init__(self, n: typing.SupportsInt, bits: collections.abc.Sequence[bool]) -> None:
        ...
    def __invert__(self) -> BitVec:
        ...
    def __ixor__(self, arg0: BitVec) -> BitVec:
        ...
    def __len__(self) -> int:
        ...
    def __lshift__(self, arg0: typing.SupportsInt) -> BitVec:
        ...
    def __or__(self, arg0: BitVec) -> BitVec:
        ...
    def __repr__(self) -> str:
        ...
    def __rshift__(self, arg0: typing.SupportsInt) -> BitVec:
        ...
    def __setitem__(self, arg0: typing.SupportsInt, arg1: bool) -> None:
        ...
    def __xor__(self, arg0: BitVec) -> BitVec:
        ...
    def count(self) -> int:
        ...
    def size(self) -> int:
        ...
    def to_list(self) -> list[bool]:
        ...
    def to_numpy(self) -> numpy.typing.NDArray[numpy.bool]:
        ...
class Matrix:
    __hash__: typing.ClassVar[None] = None
    @staticmethod
    def from_numpy(array: typing.Annotated[numpy.typing.ArrayLike, numpy.bool]) -> Matrix:
        ...
    @staticmethod
    def from_rows(rows: collections.abc.Sequence[BitVec]) -> Matrix:
        ...
    @staticmethod
    def identity(n: typing.SupportsInt) -> Matrix:
        ...
    @staticmethod
    def zeros(rows: typing.SupportsInt, cols: typing.SupportsInt) -> Matrix:
        ...
    def __add__(self, arg0: Matrix) -> Matrix:
        ...
    def __eq__(self, arg0: Matrix) -> bool:
        ...
    def __getitem__(self, arg0: typing.SupportsInt) -> BitVec:
        ...
    def __iadd__(self, arg0: Matrix) -> Matrix:
        ...
    def __init__(self, rows: typing.SupportsInt, cols: typing.SupportsInt) -> None:
        ...
    def __len__(self) -> int:
        ...
    def __matmul__(self, arg0: BitVec) -> BitVec:
        ...
    def __mul__(self, arg0: Matrix) -> Matrix:
        ...
    def __ne__(self, arg0: Matrix) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setitem__(self, arg0: typing.SupportsInt, arg1: BitVec) -> None:
        ...
    def append_down_inplace(self, rhs: Matrix) -> Matrix:
        ...
    def append_right_inplace(self, rhs: Matrix) -> Matrix:
        ...
    def get_row(self, arg0: typing.SupportsInt) -> BitVec:
        ...
    def mul_vec_left(self: BitVec, arg0: Matrix) -> BitVec:
        ...
    def reserve_rows(self, n: typing.SupportsInt) -> None:
        ...
    def set_row(self, arg0: typing.SupportsInt, arg1: BitVec) -> None:
        ...
    def shrink_to_fit(self) -> None:
        ...
    def to_numpy(self) -> numpy.typing.NDArray[numpy.bool]:
        ...
    def transpose(self) -> Matrix:
        ...
    @property
    def cols(self) -> int:
        ...
    @property
    def rows(self) -> int:
        ...
class NullSpace:
    def P_ref(self) -> Matrix:
        ...
    def apply(self, y: BitVec) -> Matrix:
        ...
    def basis_ref(self) -> Matrix:
        ...
    def rank_divergence(self, y: BitVec) -> int:
        ...
    def vector_ref(self) -> BitVec:
        ...
    @property
    def P(self) -> Matrix:
        ...
    @property
    def basis(self) -> Matrix:
        ...
    @property
    def z(self) -> BitVec:
        ...
class PivotMap:
    def __repr__(self: collections.abc.Mapping[typing.SupportsInt, typing.SupportsInt]) -> str:
        ...
class Tensor3D:
    __hash__: typing.ClassVar[None] = None
    @staticmethod
    def from_numpy(array: typing.Annotated[numpy.typing.ArrayLike, numpy.bool]) -> Tensor3D:
        ...
    def __eq__(self, arg0: Tensor3D) -> bool:
        ...
    @typing.overload
    def __init__(self, n: typing.SupportsInt) -> None:
        ...
    @typing.overload
    def __init__(self, matrix: Matrix) -> None:
        ...
    def __ne__(self, arg0: Tensor3D) -> bool:
        ...
    def get(self, i: typing.SupportsInt, j: typing.SupportsInt, k: typing.SupportsInt) -> bool:
        ...
    def to_numpy(self) -> numpy.typing.NDArray[numpy.bool]:
        ...
    @property
    def n(self) -> int:
        ...
class ToddGenerator:
    def __init__(self, P: Matrix) -> None:
        ...
    def make(self, z: BitVec) -> NullSpace:
        ...
    def make1(self, row: typing.SupportsInt) -> NullSpace:
        ...
    def make2(self, row1: typing.SupportsInt, row2: typing.SupportsInt) -> NullSpace:
        ...
    @property
    def P(self) -> Matrix:
        ...
class TohpeGenerator:
    def __init__(self, P: Matrix) -> None:
        ...
    def make(self, z: BitVec) -> NullSpace:
        ...
    def make1(self, row: typing.SupportsInt) -> NullSpace:
        ...
    def make2(self, row1: typing.SupportsInt, row2: typing.SupportsInt) -> NullSpace:
        ...
    @property
    def P(self) -> Matrix:
        ...
def L_expansion(mat: Matrix) -> Matrix:
    """
    Apply L-expansion transform to 'mat' and return the expanded matrix.
    """
def build_X(z: BitVec) -> Matrix:
    """
    Build the X(z) matrix from bit-vector z (over GF(2)).
    """
def build_v(z: BitVec) -> Matrix:
    """
    Build the V(z) (row) matrix from bit-vector z (quadratic terms).
    """
def eliminate_duplications_inplace(A: Matrix) -> None:
    """
    Eliminate duplicate rows over GF(2) and drop all-zero rows in place.
    Keeps each unique nonzero row exactly once; preserves GF(2) semantics.
    """
def extract_basis(basis_kernel: Matrix, pivots: collections.abc.Mapping[typing.SupportsInt, typing.SupportsInt]) -> Matrix:
    """
    Extract a basis subset of rows from 'basis_kernel' by excluding rows
    that appear as pivot rows (keys of 'pivots'). Returns a new Matrix.
    """
def gauss_elimination_inplace(A: Matrix, aug: Matrix, pivots: collections.abc.Mapping[typing.SupportsInt, typing.SupportsInt] = {}) -> None:
    """
    Perform in-place GF(2) elimination on A with augmented matrix 'aug'.
    
    Args:
      A      : Matrix to row-reduce (modified in place).
      aug    : Augmented side, modified in lockstep with A.
      pivots : dict-like {row_index -> pivot_col}; updated in place.
    Raises:
      ValueError if A.rows() != aug.rows().
    """
def swap_rows_inplace(A: Matrix, r1: typing.SupportsInt, r2: typing.SupportsInt) -> None:
    """
    Swap rows r1 and r2 of matrix A in place.
    """
